// seedReport.js
module.exports = {
  project: "Swachhta Prahari",
  dateOfReport: "September 8, 2025",
  site: "UPSIDA-Managed Sahibabad Industrial Site 4",
  preparedFor: "Designated Officials, UPSIDA",
  preparedBy: "KratiTech (Project Swachhta Prahari Team)",

  executiveSummary: `This report is an automated, camera-specific summary generated by the "Swachhta Prahari"
AI surveillance system. It details all significant incidents detected by Camera 8 over the past
24 hours. The system uses the existing CCTV infrastructure to proactively monitor and identify
environmental hazards in its field of view.
During this period, the system flagged instances of waste spillage onto the road from the
open dump site at around 5pm. Continuous monitoring of the waste level at this location
indicates the Cleanliness is not proper as dumping sites weren’t cleaned`,

  incidentLogs: `The following table details all "Swachhta" related events detected by the AI Inference Engine
for Camera 8. Each incident is logged with a unique ID, timestamp, location, and a link to
supporting visual evidence.`,
  incidents: [
    {
      id: "SPILL-0906-002",
      timestamp: "17:02:45",
      cameraId: "CAM-08",
      eventType: "Waste Spillage",
      details:
        "Waste from the open dump site has spilled onto the road, crossing the designated red-line boundary.",
      severity: "Medium",
    },
    {
      id: "DUMP-0906-001",
      timestamp: "06:00:45",
      cameraId: "CAM-08",
      eventType: "Open Dump Site Monitoring",
      details:
        "The waste level at this location indicates the cleanliness is not proper. Requires scheduling for clearance.",
      severity: "High",
    },
  ],

  analyticsLogs: `This section provides a quantitative overview and suggests operational actions based on the
events detected by Camera 8.
`,
  analytics: {
    trends: ["Waste Spillage: 1 incident", "Open Dump Site Monitoring: 1 incident"],
    analysis: [
      "The waste spillage event indicates that the open dump site is at capacity and poses a direct cleanliness risk.",
      "Continuous monitoring of the waste level at this location indicates the Cleanliness is not proper as dumping sites weren’t cleaned",
    ],
    recommendations: [
      "Immediate Action: Dispatch a cleanup crew to address the waste spillage on the road in the vicinity of Camera 8",
      " Operational Planning: Schedule immediate clearance for the open dumping area monitored by Camera 8 to mitigate further spillage and address the high fill level.",
      " Preventative Measure: The early morning dumping incident reinforces the need for installing cautionary signage in this specific area to deter future violations.",
    ],
  },

  conclusion: `The Swachhta Prahari system is operating within its designed parameters, successfully
processing video streams to provide actionable intelligence. This camera-specific report
demonstrates the platform's capability to transform passive surveillance into a proactive tool
for environmental governance. The data provided aims to support UPSIDA in optimizing
resource allocation and fostering a cleaner industrial ecosystem as envisioned by the
tripartite partnership..`,
};
